SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE TEST 
    ( 
     ID_TEST NUMBER (22)  NOT NULL , 
     DE_TEST VARCHAR2 (255)  NOT NULL
    ) 
;


CREATE UNIQUE INDEX IPKTEST_00 ON TEST 
    ( 
     ID_TEST ASC 
    ) 
;

ALTER TABLE TEST 
    ADD CONSTRAINT PKTEST_00 PRIMARY KEY ( ID_TEST ) ;