// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.Server;
import java.io.Serializable;

privileged aspect Server_Roo_Serializable {
    
    declare parents: Server implements Serializable;
    
    private static final long Server.serialVersionUID = 1L;
    
}
