// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.Application;
import java.io.Serializable;

privileged aspect Application_Roo_Serializable {
    
    declare parents: Application implements Serializable;
    
    private static final long Application.serialVersionUID = 1L;
    
}
