// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.ServerState;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ServerState_Roo_Configurable {
    
    declare @type: ServerState: @Configurable;
    
}
