// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.ServerState;
import java.io.Serializable;

privileged aspect ServerState_Roo_Serializable {
    
    declare parents: ServerState implements Serializable;
    
    private static final long ServerState.serialVersionUID = 1L;
    
}
