// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.EnvironmentDataOnDemand;
import es.jtestme.collector.domain.EnvironmentIntegrationTest;
import es.jtestme.collector.service.JTestMeCollectorService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EnvironmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EnvironmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EnvironmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EnvironmentIntegrationTest: @Transactional;
    
    @Autowired
    EnvironmentDataOnDemand EnvironmentIntegrationTest.dod;
    
    @Autowired
    JTestMeCollectorService EnvironmentIntegrationTest.jTestMeCollectorService;
    
    @Test
    public void EnvironmentIntegrationTest.testCountAllEnvironments() {
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", dod.getRandomEnvironment());
        long count = jTestMeCollectorService.countAllEnvironments();
        Assert.assertTrue("Counter for 'Environment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EnvironmentIntegrationTest.testFindEnvironment() {
        Environment obj = dod.getRandomEnvironment();
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Environment' failed to provide an identifier", id);
        obj = jTestMeCollectorService.findEnvironment(id);
        Assert.assertNotNull("Find method for 'Environment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Environment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EnvironmentIntegrationTest.testFindAllEnvironments() {
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", dod.getRandomEnvironment());
        long count = jTestMeCollectorService.countAllEnvironments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Environment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Environment> result = jTestMeCollectorService.findAllEnvironments();
        Assert.assertNotNull("Find all method for 'Environment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Environment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EnvironmentIntegrationTest.testFindEnvironmentEntries() {
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", dod.getRandomEnvironment());
        long count = jTestMeCollectorService.countAllEnvironments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Environment> result = jTestMeCollectorService.findEnvironmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Environment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Environment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EnvironmentIntegrationTest.testFlush() {
        Environment obj = dod.getRandomEnvironment();
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Environment' failed to provide an identifier", id);
        obj = jTestMeCollectorService.findEnvironment(id);
        Assert.assertNotNull("Find method for 'Environment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEnvironment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Environment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EnvironmentIntegrationTest.testUpdateEnvironmentUpdate() {
        Environment obj = dod.getRandomEnvironment();
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Environment' failed to provide an identifier", id);
        obj = jTestMeCollectorService.findEnvironment(id);
        boolean modified =  dod.modifyEnvironment(obj);
        Integer currentVersion = obj.getVersion();
        Environment merged = jTestMeCollectorService.updateEnvironment(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Environment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EnvironmentIntegrationTest.testSaveEnvironment() {
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", dod.getRandomEnvironment());
        Environment obj = dod.getNewTransientEnvironment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Environment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Environment' identifier to be null", obj.getId());
        jTestMeCollectorService.saveEnvironment(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Environment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EnvironmentIntegrationTest.testDeleteEnvironment() {
        Environment obj = dod.getRandomEnvironment();
        Assert.assertNotNull("Data on demand for 'Environment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Environment' failed to provide an identifier", id);
        obj = jTestMeCollectorService.findEnvironment(id);
        jTestMeCollectorService.deleteEnvironment(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Environment' with identifier '" + id + "'", jTestMeCollectorService.findEnvironment(id));
    }
    
}
