// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.ServerState;
import es.jtestme.collector.domain.ServerStateDataOnDemand;
import es.jtestme.collector.domain.ServerStateIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServerStateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServerStateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServerStateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServerStateIntegrationTest: @Transactional;
    
    @Autowired
    ServerStateDataOnDemand ServerStateIntegrationTest.dod;
    
    @Test
    public void ServerStateIntegrationTest.testCountServerStates() {
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", dod.getRandomServerState());
        long count = ServerState.countServerStates();
        Assert.assertTrue("Counter for 'ServerState' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServerStateIntegrationTest.testFindServerState() {
        ServerState obj = dod.getRandomServerState();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to provide an identifier", id);
        obj = ServerState.findServerState(id);
        Assert.assertNotNull("Find method for 'ServerState' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ServerState' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServerStateIntegrationTest.testFindAllServerStates() {
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", dod.getRandomServerState());
        long count = ServerState.countServerStates();
        Assert.assertTrue("Too expensive to perform a find all test for 'ServerState', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ServerState> result = ServerState.findAllServerStates();
        Assert.assertNotNull("Find all method for 'ServerState' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ServerState' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServerStateIntegrationTest.testFindServerStateEntries() {
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", dod.getRandomServerState());
        long count = ServerState.countServerStates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ServerState> result = ServerState.findServerStateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ServerState' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ServerState' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServerStateIntegrationTest.testFlush() {
        ServerState obj = dod.getRandomServerState();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to provide an identifier", id);
        obj = ServerState.findServerState(id);
        Assert.assertNotNull("Find method for 'ServerState' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServerState(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ServerState' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServerStateIntegrationTest.testMergeUpdate() {
        ServerState obj = dod.getRandomServerState();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to provide an identifier", id);
        obj = ServerState.findServerState(id);
        boolean modified =  dod.modifyServerState(obj);
        Integer currentVersion = obj.getVersion();
        ServerState merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ServerState' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServerStateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", dod.getRandomServerState());
        ServerState obj = dod.getNewTransientServerState(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ServerState' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ServerState' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ServerState' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServerStateIntegrationTest.testRemove() {
        ServerState obj = dod.getRandomServerState();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerState' failed to provide an identifier", id);
        obj = ServerState.findServerState(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ServerState' with identifier '" + id + "'", ServerState.findServerState(id));
    }
    
}
