// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.ApplicationState;
import es.jtestme.collector.domain.ApplicationStateDataOnDemand;
import es.jtestme.collector.domain.ApplicationStateIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ApplicationStateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ApplicationStateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ApplicationStateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ApplicationStateIntegrationTest: @Transactional;
    
    @Autowired
    ApplicationStateDataOnDemand ApplicationStateIntegrationTest.dod;
    
    @Test
    public void ApplicationStateIntegrationTest.testCountApplicationStates() {
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", dod.getRandomApplicationState());
        long count = ApplicationState.countApplicationStates();
        Assert.assertTrue("Counter for 'ApplicationState' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testFindApplicationState() {
        ApplicationState obj = dod.getRandomApplicationState();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to provide an identifier", id);
        obj = ApplicationState.findApplicationState(id);
        Assert.assertNotNull("Find method for 'ApplicationState' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ApplicationState' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testFindAllApplicationStates() {
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", dod.getRandomApplicationState());
        long count = ApplicationState.countApplicationStates();
        Assert.assertTrue("Too expensive to perform a find all test for 'ApplicationState', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ApplicationState> result = ApplicationState.findAllApplicationStates();
        Assert.assertNotNull("Find all method for 'ApplicationState' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ApplicationState' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testFindApplicationStateEntries() {
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", dod.getRandomApplicationState());
        long count = ApplicationState.countApplicationStates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ApplicationState> result = ApplicationState.findApplicationStateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ApplicationState' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ApplicationState' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testFlush() {
        ApplicationState obj = dod.getRandomApplicationState();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to provide an identifier", id);
        obj = ApplicationState.findApplicationState(id);
        Assert.assertNotNull("Find method for 'ApplicationState' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApplicationState(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ApplicationState' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testMergeUpdate() {
        ApplicationState obj = dod.getRandomApplicationState();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to provide an identifier", id);
        obj = ApplicationState.findApplicationState(id);
        boolean modified =  dod.modifyApplicationState(obj);
        Integer currentVersion = obj.getVersion();
        ApplicationState merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ApplicationState' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", dod.getRandomApplicationState());
        ApplicationState obj = dod.getNewTransientApplicationState(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ApplicationState' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ApplicationState' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ApplicationStateIntegrationTest.testRemove() {
        ApplicationState obj = dod.getRandomApplicationState();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ApplicationState' failed to provide an identifier", id);
        obj = ApplicationState.findApplicationState(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ApplicationState' with identifier '" + id + "'", ApplicationState.findApplicationState(id));
    }
    
}
