// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.Application;
import es.jtestme.collector.domain.ApplicationDataOnDemand;
import es.jtestme.collector.domain.ApplicationState;
import es.jtestme.collector.domain.ApplicationStateDataOnDemand;
import es.jtestme.collector.domain.reference.StateType;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ApplicationStateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ApplicationStateDataOnDemand: @Component;
    
    private Random ApplicationStateDataOnDemand.rnd = new SecureRandom();
    
    private List<ApplicationState> ApplicationStateDataOnDemand.data;
    
    @Autowired
    ApplicationDataOnDemand ApplicationStateDataOnDemand.applicationDataOnDemand;
    
    public ApplicationState ApplicationStateDataOnDemand.getNewTransientApplicationState(int index) {
        ApplicationState obj = new ApplicationState();
        setApplication(obj, index);
        setStateDate(obj, index);
        setStateType(obj, index);
        return obj;
    }
    
    public void ApplicationStateDataOnDemand.setApplication(ApplicationState obj, int index) {
        Application application = applicationDataOnDemand.getRandomApplication();
        obj.setApplication(application);
    }
    
    public void ApplicationStateDataOnDemand.setStateDate(ApplicationState obj, int index) {
        Date stateDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStateDate(stateDate);
    }
    
    public void ApplicationStateDataOnDemand.setStateType(ApplicationState obj, int index) {
        StateType stateType = StateType.class.getEnumConstants()[0];
        obj.setStateType(stateType);
    }
    
    public ApplicationState ApplicationStateDataOnDemand.getSpecificApplicationState(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ApplicationState obj = data.get(index);
        Long id = obj.getId();
        return ApplicationState.findApplicationState(id);
    }
    
    public ApplicationState ApplicationStateDataOnDemand.getRandomApplicationState() {
        init();
        ApplicationState obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ApplicationState.findApplicationState(id);
    }
    
    public boolean ApplicationStateDataOnDemand.modifyApplicationState(ApplicationState obj) {
        return false;
    }
    
    public void ApplicationStateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ApplicationState.findApplicationStateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ApplicationState' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ApplicationState>();
        for (int i = 0; i < 10; i++) {
            ApplicationState obj = getNewTransientApplicationState(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
