// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.Application;
import es.jtestme.collector.domain.ApplicationDataOnDemand;
import es.jtestme.collector.domain.reference.EnvironmentType;
import es.jtestme.collector.service.JTestMeCollectorService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ApplicationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ApplicationDataOnDemand: @Component;
    
    private Random ApplicationDataOnDemand.rnd = new SecureRandom();
    
    private List<Application> ApplicationDataOnDemand.data;
    
    @Autowired
    JTestMeCollectorService ApplicationDataOnDemand.jTestMeCollectorService;
    
    public Application ApplicationDataOnDemand.getNewTransientApplication(int index) {
        Application obj = new Application();
        setDescription(obj, index);
        setEnvironmentType(obj, index);
        setMailingError(obj, index);
        setMailingNoConnect(obj, index);
        setName(obj, index);
        setPassword(obj, index);
        setStartWatching(obj, index);
        setUrl(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void ApplicationDataOnDemand.setDescription(Application obj, int index) {
        String description = "description_" + index;
        if (description.length() > 250) {
            description = description.substring(0, 250);
        }
        obj.setDescription(description);
    }
    
    public void ApplicationDataOnDemand.setEnvironmentType(Application obj, int index) {
        EnvironmentType environmentType = EnvironmentType.class.getEnumConstants()[0];
        obj.setEnvironmentType(environmentType);
    }
    
    public void ApplicationDataOnDemand.setMailingError(Application obj, int index) {
        Boolean mailingError = true;
        obj.setMailingError(mailingError);
    }
    
    public void ApplicationDataOnDemand.setMailingNoConnect(Application obj, int index) {
        Boolean mailingNoConnect = true;
        obj.setMailingNoConnect(mailingNoConnect);
    }
    
    public void ApplicationDataOnDemand.setName(Application obj, int index) {
        String name = "name_" + index;
        if (name.length() > 30) {
            name = name.substring(0, 30);
        }
        obj.setName(name);
    }
    
    public void ApplicationDataOnDemand.setPassword(Application obj, int index) {
        String password = "password_" + index;
        if (password.length() > 50) {
            password = password.substring(0, 50);
        }
        obj.setPassword(password);
    }
    
    public void ApplicationDataOnDemand.setStartWatching(Application obj, int index) {
        Boolean startWatching = true;
        obj.setStartWatching(startWatching);
    }
    
    public void ApplicationDataOnDemand.setUrl(Application obj, int index) {
        String url = "url_" + index;
        if (url.length() > 250) {
            url = url.substring(0, 250);
        }
        obj.setUrl(url);
    }
    
    public void ApplicationDataOnDemand.setUsername(Application obj, int index) {
        String username = "username_" + index;
        if (username.length() > 50) {
            username = username.substring(0, 50);
        }
        obj.setUsername(username);
    }
    
    public Application ApplicationDataOnDemand.getSpecificApplication(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Application obj = data.get(index);
        Long id = obj.getId();
        return jTestMeCollectorService.findApplication(id);
    }
    
    public Application ApplicationDataOnDemand.getRandomApplication() {
        init();
        Application obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return jTestMeCollectorService.findApplication(id);
    }
    
    public boolean ApplicationDataOnDemand.modifyApplication(Application obj) {
        return false;
    }
    
    public void ApplicationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = jTestMeCollectorService.findApplicationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Application' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Application>();
        for (int i = 0; i < 10; i++) {
            Application obj = getNewTransientApplication(i);
            try {
                jTestMeCollectorService.saveApplication(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
