// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jtestme.collector.domain;

import es.jtestme.collector.domain.Verificator;
import es.jtestme.collector.domain.VerificatorDataOnDemand;
import es.jtestme.collector.domain.VerificatorIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VerificatorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VerificatorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VerificatorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VerificatorIntegrationTest: @Transactional;
    
    @Autowired
    VerificatorDataOnDemand VerificatorIntegrationTest.dod;
    
    @Test
    public void VerificatorIntegrationTest.testCountVerificators() {
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", dod.getRandomVerificator());
        long count = Verificator.countVerificators();
        Assert.assertTrue("Counter for 'Verificator' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VerificatorIntegrationTest.testFindVerificator() {
        Verificator obj = dod.getRandomVerificator();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to provide an identifier", id);
        obj = Verificator.findVerificator(id);
        Assert.assertNotNull("Find method for 'Verificator' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Verificator' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VerificatorIntegrationTest.testFindAllVerificators() {
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", dod.getRandomVerificator());
        long count = Verificator.countVerificators();
        Assert.assertTrue("Too expensive to perform a find all test for 'Verificator', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Verificator> result = Verificator.findAllVerificators();
        Assert.assertNotNull("Find all method for 'Verificator' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Verificator' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VerificatorIntegrationTest.testFindVerificatorEntries() {
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", dod.getRandomVerificator());
        long count = Verificator.countVerificators();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Verificator> result = Verificator.findVerificatorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Verificator' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Verificator' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VerificatorIntegrationTest.testFlush() {
        Verificator obj = dod.getRandomVerificator();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to provide an identifier", id);
        obj = Verificator.findVerificator(id);
        Assert.assertNotNull("Find method for 'Verificator' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVerificator(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Verificator' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VerificatorIntegrationTest.testMergeUpdate() {
        Verificator obj = dod.getRandomVerificator();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to provide an identifier", id);
        obj = Verificator.findVerificator(id);
        boolean modified =  dod.modifyVerificator(obj);
        Integer currentVersion = obj.getVersion();
        Verificator merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Verificator' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VerificatorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", dod.getRandomVerificator());
        Verificator obj = dod.getNewTransientVerificator(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Verificator' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Verificator' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Verificator' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VerificatorIntegrationTest.testRemove() {
        Verificator obj = dod.getRandomVerificator();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Verificator' failed to provide an identifier", id);
        obj = Verificator.findVerificator(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Verificator' with identifier '" + id + "'", Verificator.findVerificator(id));
    }
    
}
